services:
  db:
    image: postgres:17
    ports:
      - 5432:5432
    networks:
      - web_backend
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bookstore_dev
      - POSTGRES_PASSWORD=bookstore_dev
      - POSTGRES_DB=bookstore_dev_db

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - app_data:/usr/src/app/
    ports:
      - 8000:8000
    networks:
      - web_backend
    env_file:
      - ./env.dev
    depends_on:
      - db

networks:
  web_backend:
    driver: bridge

volumes:
  postgres_data:
  app_data: