name: Python Pull Request Workflow
on: [pull_request, push]
jobs:

  qa:
    name: Quality check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: 3.10.12
      - name: Install poetry
        run: |
          pip install pip
          pip install poetry
          poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: View poetry --help
        run: poetry --help

      - name: Install dependencies
        shell: bash
        run: python -m poetry install

      - name: Test
        run: |
          poetry run python manage.py test
      - name: Wemake Python Stylguide
        uses: wemake-services/wemake-python-styleguide@1.3.0
        continue-on-error: true
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}